---
title: "Code-PS3"
author: "Kekun Han"
date: "11/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,include=FALSE}
library(tidyverse)
library(haven)

# Read in the raw data 
raw_data_t <- read_dta("ns20200625/ns20200625.dta")
# Add the labels
raw_data_t <- labelled::to_factor(raw_data_t)
# Just keep some variables
reduced_data_t <- 
  raw_data_t %>% 
  select(registration,
         vote_2020,
         language,
         employment,
         gender,
         census_region,
         hispanic,
         race_ethnicity,
         household_income,
         education,
         state,
         age)

#Cleaning the data for post-stratification later

reduced_data_t <-
  reduced_data_t %>%
  mutate(vote_trump = 
           ifelse(vote_2020 =="Donald Trump", 1, 0)) %>% 
  mutate(vote_biden =
           ifelse(vote_2020 =="Joe Biden", 1, 0))%>%
  mutate(Registration = 
           ifelse(registration == "Registered", 1, 0)) %>%
  mutate(age_group = case_when(age <= 30 ~ '18to30',
                              age > 30 & age <= 40 ~ "31to40",
                              age > 40 & age <= 50 ~ "41to50",
                              age > 50 & age <= 60 ~ "51to60",
                              age > 60 ~ "60plus")) %>%
  select(-vote_2020,-registration, -age) 
  
reduced_data_t <-
  reduced_data_t %>%
  mutate(Race = case_when(race_ethnicity == "White" ~ "White", race_ethnicity == "Black, or African American" ~ "Black, or African American", race_ethnicity == "American Indian or Alaska Native" ~ "American Indian or Alaska Native", race_ethnicity == "Asian (Chinese)" ~ "Asian (Chinese)", race_ethnicity == "Asian (Japanese)" ~ "Asian (Japanese)", race_ethnicity == "Asian (Asian Indian)" | race_ethnicity =="Asian (Filipino)" | race_ethnicity =="Asian (Korean)" | race_ethnicity =="Asian (Vietnamese)" | race_ethnicity =="Asian (Other)" | race_ethnicity =="Pacific Islander (Native Hawaiian)" | race_ethnicity =="Pacific Islander (Guamanian)" | race_ethnicity =="Pacific Islander (Samoan)" | race_ethnicity =="Pacific Islander (Other)"  ~ "Other Asian or Pacific Islander", race_ethnicity == "Some other race" ~ "Some other race")) %>%
  select(-race_ethnicity)

reduced_data_t <-
  reduced_data_t %>%
  mutate(Hispanic = case_when(hispanic == "Not Hispanic" ~ "not hispanic", hispanic == "Mexican" ~ "mexican", hispanic == "Cuban" ~ "cuban", hispanic == "Puerto Rican" ~ "puerto rican", hispanic == "Argentinian" | hispanic =="Colombian" | hispanic =="Ecuadorian" | hispanic =="Salvadorean" | hispanic =="Guatemalan" | hispanic =="Nicaraguan" | hispanic =="Panamanian" | hispanic =="Peruvian" | hispanic =="Spanish" | hispanic =="Venezuelan" | hispanic =="Other Hispanic" ~ "other")) %>%
  select(-hispanic)

reduced_data_t <-
  reduced_data_t %>%
  mutate(Employment = case_when(employment == "Full-time employed" | employment =="Part-time employed" | employment =="Self_employed" ~ "employed", employment == "Homemaker" | employment =="Retired" | employment =="Permanently disabled" | employment =="Student" | employment =="Other" ~ "not in labor force", employment == "Unemployed or temporarily on layoff" ~ "unemployed")) %>%
  select(-employment)

reduced_data_t <-
  reduced_data_t %>%
  mutate(Education = case_when(education == "3rd Grade or less" | education == "Middle School - Grades 4 - 8" ~ "Middle School or less", education == "Completed some high school" ~ "Completed some high school", education == "High school graduate" ~ "High school graduate", education == "Other post high school vocational training" | education == "Completed some college, but no degree" | education == "Completed some graduate, but no degree" ~ "Some College", education == "Associate Degree" ~ "Associate Degree", education == "College Degree (such as B.A., B.S.)" ~ "College Degree (such as B.A., B.S.)", education == "Masters degree" | education == "Doctorate degree" ~ "Beyond College" )) %>%
  select(-education)
    
reduced_data_t <- reduced_data_t %>%
  mutate(sex = case_when(gender == "Female" ~ "female", gender == "Male" ~ "male")) %>%
  select(-gender)

reduced_data_t <- reduced_data_t[!(reduced_data_t$Registration == 0),]
reduced_data_t <- reduced_data_t %>% select(-Registration)
  
reduced_data_t <- reduced_data_t %>%
  na.omit()  

# Saving the survey/sample data as a csv file in my
# working directory
write_csv(reduced_data_t, "survey_data.csv")
```

```{r,include=FALSE}
raw_data_p <- read_dta("usa_00002.dta.gz")


# Add the labels
raw_data_p <- labelled::to_factor(raw_data_p)
```

```{r,include=FALSE}
reduced_data_p <- 
  raw_data_p %>% 
  select(region,
         age, 
         race, 
         educ,
         sex,
         hispan,
         empstat)
      

#Modify the census data into the same scale and format as the survey data

reduced_data_p$age <- as.integer(reduced_data_p$age)
reduced_data_p <- reduced_data_p[!(reduced_data_p$age < 18),] 

reduced_data_p <- reduced_data_p %>%
  mutate(age_group = case_when(age <= 30 ~ '18to30',
                              age > 30 & age <= 40 ~ "31to40",
                              age > 40 & age <= 50 ~ "41to50",
                              age > 50 & age <= 60 ~ "51to60",
                              age > 60 ~ "60plus"))

reduced_data_p <- reduced_data_p %>%
  mutate(census_region = case_when(region == "new england division" | region == "middle atlantic division" ~ 'Northeast',
                              region == "west north central div" | region == "east north central div" ~ "Midwest",
                              region == "pacific division" | region == "mountain division" ~ "West",
                              region ==  "west south central div" | region == "east south central div" | region == "south atlantic division" ~ "South"))


reduced_data_p <- reduced_data_p %>%
  mutate(Race = case_when(race == "white" ~ "White", race == "black/african american/negro" ~ "Black, or African American", race == "american indian or alaska native" ~ "American Indian or Alaska Native", race == "chinese" ~ "Asian (Chinese)", race == "japanese" ~ "Asian (Japanese)", race == "other asian or pacific islander" ~ "Other Asian or Pacific Islander", race == "other race, nec" | race =="two major races" | race =="three or more major races" ~ "Some other race"))


reduced_data_p <- reduced_data_p %>%
  mutate(Education = case_when(educ == "n/a or no schooling" | educ =="nursery school to grade 4" | educ =="grade 5, 6, 7, or 8" ~ "Middle School or less", educ == "grade 9" | educ == "grade 10" | educ == "grade 11" ~ "Completed some high school", educ == "grade 12" ~ "High school graduate", educ == "1 year of college" | educ == "2 years of college" | educ == "3 years of college" ~ "Some College", educ == "4 years of college" ~ "College Degree (such as B.A., B.S.)", educ == "5+ years of college" ~ "Beyond College"))


reduced_data_p <- reduced_data_p %>%
   rename(Hispanic = hispan,
          Employment = empstat)


reduced_data_p <- 
  reduced_data_p %>%
  count(age_group,census_region,Race,Education,sex,Hispanic, Employment) %>%
  group_by(age_group,census_region,Race,Education,sex,Hispanic, Employment) 
# Saving the census data as a csv file in my
# working directory
write_csv(reduced_data_p, "census_data.csv")


```

```{r setup, include=FALSE}

# Loading in the cleaned survey Data
survey_data <- read_csv("survey_data.csv")

# Loading in the cleaned census Data
census_data <- read_csv("census_data.csv")

```


```{r,include=FALSE}
library(lme4)
#Build the full logistic model for variable selection
fullmodel <- glm(vote_trump ~ language + Employment + sex + Hispanic + Race + household_income + Education + age_group + state + census_region, data = survey_data, family = binomial)

summary(fullmodel)

```

```{r,include=FALSE}
#Using backward selection
b_step.model <- fullmodel %>% MASS::stepAIC(trace = FALSE, direction = "backward")
coef(b_step.model)
### Backward selection selects employment, hispanic, sex, race, household income, education, age_group, census_region
```

```{r,include=FALSE}
#Using forward selection
f_step.model <- fullmodel %>% MASS::stepAIC(trace = FALSE, direction = "forward")
coef(f_step.model)
```

```{r,include=FALSE}
c(AIC(b_step.model),BIC(b_step.model))

c(AIC(fullmodel),BIC(fullmodel))


```


```{r,include=FALSE}
### Select the model chosen by backward selection because it has the lowerst AIC and BIC.
### Build the selected model
b_model <- glm(vote_trump ~ Employment + sex + Hispanic + Race + household_income + Education + age_group + census_region, data = survey_data, family = binomial)

summary(b_model)
```

```{r,include=FALSE}
### Check for multicollinearity
car::vif(b_model)
```


```{r,include=FALSE}
## Variable household_income is droped because it does have a match with census data.
## The model which predicts the probability of vote for Trump.
F_model_T <- glm(vote_trump ~ Employment + sex + Hispanic + Race + Education + age_group + census_region, data = survey_data, family = binomial)

summary(F_model_T)
```


```{r,include=FALSE}
## The model which predicts the probability of vote for Biden. It has the exactly same predictors as the model which predict for Trump
F_model_B <- glm(vote_biden ~ Employment + sex + Hispanic + Race + Education + age_group + census_region, data = survey_data, family = binomial)

summary(F_model_B)
```

```{r,include=FALSE}


### Implement post-stratification

### Probability of voting Trump
census_data$logodds_estimate_t <-
  F_model_T %>%
  predict(newdata = census_data)

census_data$estimate_t <-
  exp(census_data$logodds_estimate_t)/(1+exp(census_data$logodds_estimate_t))

census_data %>%
  mutate(alp_predict_prop_t = estimate_t*n) %>%
  summarise(alp_predict_t = sum(alp_predict_prop_t)/sum(n))

### Probability of voting Biden
census_data$logodds_estimate_b <-
  F_model_B %>%
  predict(newdata = census_data)

census_data$estimate_b <-
  exp(census_data$logodds_estimate_b)/(1+exp(census_data$logodds_estimate_b))

census_data %>%
  mutate(alp_predict_prop_b = estimate_b*n) %>%
  summarise(alp_predict_b = sum(alp_predict_prop_b)/sum(n))
```